services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile

    container_name: warehouse-api
    command: sh /start-reload.sh
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: "utils/environments/db.env"
    # secrets:
    #  - db_password



  postgres:
    image: postgres:latest
    container_name: postgres-for-warehouse-api
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

    env_file: "utils/environments/db.env"

    environment:
      POSTGRES_NAME: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres} # db_password.txt
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3

    # secrets:
    #  - db_password


# secrets:
  #  db_password:
   #   file: utils/secrets/db_password.txt
